// app/top-colleges/page.jsx
"use client";

import React, { useState, useMemo } from "react";
import { AcademicCapIcon, MapPinIcon } from "@heroicons/react/24/solid";
// Data for Engineering Colleges - Extend this array as needed!
// data/colleges.js

// data/colleges.js

export const colleges = [
  // Andhra Pradesh
{
    name: "Indian Institute of Technology (IIT) Tirupati",
   // "",
    city: "Tirupati",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2015,
    rating: 5,
  },
  {
    name: "Andhra University College of Engineering",
   // "",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1955,
    rating: 5,
  },
  {
    name: "Jawaharlal Nehru Technological University (JNTU) Kakinada",
   // "",
    city: "Kakinada",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1946,
    rating: 5,
  },
  {
    name: "JNTU College of Engineering, Anantapur",
   // "",
    city: "Anantapur",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1946,
    rating: 4,
  },
  {
    name: "National Institute of Technology (NIT) Andhra Pradesh",
   // "",
    city: "Tadepalligudem",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2015,
    rating: 5,
  },
  {
    name: "University College of Engineering, Adikavi Nannaya University",
   // "",
    city: "Rajamahendravaram",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2006,
    rating: 4,
  },
  {
    name: "JNTU College of Engineering, Vizianagaram",
   // "",
    city: "Vizianagaram",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "Sri Venkateswara University (SVU) College of Engineering, Tirupati",
   // "",
    city: "Tirupati",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1971,
    rating: 4,
  },

  // Leading Private Engineering Colleges
  {
    name: "KL University",
   // "",
    city: "Guntur",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 5,
  },
  {
    name: "VIT-AP University",
   // "",
    city: "Amaravati",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 5,
  },
  {
    name: "SRM University AP",
   // "",
    city: "Amaravati",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 5,
  },
  {
    name: "Vignan's Foundation for Science, Technology and Research",
   // "",
    city: "Guntur",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1997,
    rating: 5,
  },
  {
    name: "GITAM University (Deemed to be University)",
   // "",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 5,
  },
  {
    name: "VR Siddhartha Engineering College",
   // "",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 4,
  },
  {
    name: "GMR Institute of Technology",
   // "",
    city: "Rajam",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1997,
    rating: 4,
  },
  {
    name: "Ideal Institute of Technology",
   // "",
    city: "Kakinada",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2001,
    rating: 4,
  },
  {
    name: "PACE Institute of Technology & Sciences",
   // "",
    city: "Ongole",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2007,
    rating: 4,
  },

  // District-wise Key Engineering Colleges
  {
    name: "JNTU College of Engineering, Anantapur",
   // "",
    city: "Anantapur",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1946,
    rating: 4,
  },
  {
    name: "Sri Venkateswara University (SVU) College of Engineering",
   // "",
    city: "Tirupati",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1971,
    rating: 4,
  },
  {
    name: "JNTU College of Engineering, Kakinada",
   // "",
    city: "Kakinada",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1946,
    rating: 4,
  },
  {
    name: "KL University",
   // "",
    city: "Guntur",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 5,
  },
  {
    name: "Vignan's Foundation for Science and Technology",
   // "",
    city: "Guntur",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1997,
    rating: 5,
  },
  {
    name: "VR Siddhartha Engineering College",
   // "",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 4,
  },
  {
    name: "G. Pulla Reddy Engineering College",
   // "",
    city: "Kurnool",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 4,
  },
  {
    name: "Brahmaiah College of Engineering",
   // "",
    city: "Nellore",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1971,
    rating: 4,
  },
  {
    name: "Andhra University College of Engineering",
   // "",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1955,
    rating: 5,
  },
  {
    name: "GITAM University",
   // "",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 5,
  },
  {
    name: "JNTU College of Engineering, Vizianagaram",
   // "",
    city: "Vizianagaram",
    state: "Andhra Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "Sagi Ramakrishna Raju (SRKR) Engineering College",
   // "",
    city: "West Godavari",
    state: "Andhra Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 4,
  },

   // Government
  {
    name: "Indian Institute of Technology (IIT), Patna",
   // "./indian-institute-of-technology-664c6ed9dc611",
    city: "Patna",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT), Patna",
   // "./national-institute-of-technology-664c6ed9db9ab",
    city: "Patna",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2004,
    rating: 5,
  },
  {
    name: "Muzaffarpur Institute of Technology",
   // "./muzaffarpur-institute-of-technology-664c6ed9dcb7f",
    city: "Muzaffarpur",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1954,
    rating: 5,
  },
  {
    name: "Bakhtiyarpur College of Engineering",
   // "./bakhtiyarpur-college-of-engineering-664c6ed9db09a",
    city: "Patna",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4,
  },
  {
    name: "Gaya College of Engineering",
   // "",
    city: "Gaya",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Darbhanga College of Engineering",
   // "",
    city: "Darbhanga",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Loknayak Jai Prakash Institute of Technology",
   // "",
    city: "Chhapra",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2012,
    rating: 4,
  },
  {
    name: "Bhagalpur College of Engineering",
   // "./bhagalpur-college-of-engineering-664c6ed9db506",
    city: "Bhagalpur",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1960,
    rating: 5,
  },
  {
    name: "Government Engineering College, Bhojpur",
   // "",
    city: "Bhojpur",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Government Engineering College, Vaishali",
   // "",
    city: "Vaishali",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Government Engineering College, Purnea",
   // "",
    city: "Purnea",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Kaimur",
   // "",
    city: "Kaimur",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4,
  },
  {
    name: "Government Engineering College, Madhubani",
   // "",
    city: "Madhubani",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4,
  },
  {
    name: "Government Engineering College, Supaul",
   // "",
    city: "Supaul",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Jamui",
   // "",
    city: "Jamui",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Government Engineering College, Sheikhpura",
   // "",
    city: "Sheikhpura",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Siwan",
   // "",
    city: "Siwan",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Saharsa",
   // "",
    city: "Saharsa",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Jehanabad",
   // "",
    city: "Jehanabad",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Government Engineering College, Nalanda",
   // "",
    city: "Nalanda",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Government Engineering College, Kishanganj",
   // "",
    city: "Kishanganj",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Aurangabad",
   // "",
    city: "Aurangabad",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Government Engineering College, Munger",
   // "",
    city: "Munger",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },
  {
    name: "Netaji Subhas Institute of Technology, Patna",
   // "",
    city: "Patna",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2007,
    rating: 4,
  },
  {
    name: "Shri Phanishwar Nath Renu Engineering College, Araria",
   // "",
    city: "Araria",
    state: "Bihar",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2019,
    rating: 4,
  },

  // Major Private and PPP
  {
    name: "Birla Institute of Technology, Patna Extension Centre (BIT Patna)",
   // "",
    city: "Patna",
    state: "Bihar",
    type: "Private/PPP",
    accreditations: ["AICTE"],
    established: 2006,
    rating: 5,
  },
  {
    name: "IIIT Bhagalpur (Indian Institute of Information Technology)",
   // "./indian-institute-of-information-technology-664c6ed9dbf83",
    city: "Bhagalpur",
    state: "Bihar",
    type: "PPP",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 5,
  },
  {
    name: "Amity University, Patna",
   // "",
    city: "Patna",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 4,
  },
  {
    name: "Dr. C.V. Raman University, Bihar",
   // "",
    city: "Vaishali",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 4,
  },
  {
    name: "Maulana Azad College of Engineering & Technology, Patna",
   // "",
    city: "Patna",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1987,
    rating: 4,
  },
  {
    name: "KK University, Nalanda",
   // "",
    city: "Nalanda",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 4,
  },
  {
    name: "Sandip University, Madhubani",
   // "./sandip-university-664c6eda00f02",
    city: "Madhubani",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE", "UGC", "SBTE"],
    established: 2017,
    rating: 5,
  },
  {
    name: "R.P. Sharma Institute of Technology, Patna",
   // "./r.p.-sharma-institute-of-technology-664c6ed9dd23a",
    city: "Patna",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1980,
    rating: 5,
  },
  {
    name: "Vidya Vihar Institute of Technology",
   // "",
    city: "Purnea",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 4,
  },
  {
    name: "Sityog Institute of Technology",
   // "./sityog-institute-of-technology-664c6ed9ddec3",
    city: "Aurangabad",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2011,
    rating: 5,
  },
  {
    name: "Adwaita Mission Institute of Technology, Banka",
   // "",
    city: "Banka",
    state: "Bihar",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },

  // Chhattisgarh
  // Top Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT) Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2005,
    rating: 5,
  },
  {
    name: "International Institute of Information Technology (IIIT) Naya Raipur",
   // "",
    city: "Naya Raipur",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 5,
  },
  {
    name: "Government Engineering College, Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1986,
    rating: 4,
  },
  {
    name: "Guru Ghasidas Vishwavidyalaya, Bilaspur",
   // "",
    city: "Bilaspur",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Bhilai Institute of Technology (BIT), Durg",
   // "",
    city: "Durg",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1986,
    rating: 4,
  },
  {
    name: "Chhattisgarh Swami Vivekanand Technical University (CSVTU), Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2005,
    rating: 4,
  },

  // Notable Private Engineering Colleges
  {
    name: "Rungta College of Engineering and Technology, Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1996,
    rating: 5,
  },
  {
    name: "OP Jindal University (OPJU), Raigarh",
   // "",
    city: "Raigarh",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2012,
    rating: 5,
  },
  {
    name: "Amity University, Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "Shri Shankaracharya Technical Campus (SSTC), Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Raipur Institute of Technology (RIT), Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 4,
  },
  {
    name: "C.V. Raman College of Engineering, Bilaspur",
   // "",
    city: "Bilaspur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2006,
    rating: 4,
  },
  {
    name: "MATS University, Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2006,
    rating: 4,
  },
  {
    name: "Sanjay Rungta Group of Institutions, Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2006,
    rating: 4,
  },
  {
    name: "SSGI, Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "SSIPMT, Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2012,
    rating: 4,
  },
  {
    name: "RCET, Bhilai",
   // "",
    city: "Bhilai",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 4,
  },
  {
    name: "RITEE Group of Institutions, Raipur",
   // "",
    city: "Raipur",
    state: "Chhattisgarh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 4,
  },

  // Delhi
// Major Government & Centrally Funded Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Delhi",
   // "./indian-institute-of-technology-664c6ed9dc611",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1961,
    rating: 5,
  },
  {
    name: "Delhi Technological University (DTU)",
   // "./delhi-technological-university-(dtu)--664c6ed9f1007",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1941,
    rating: 5,
  },
  {
    name: "Netaji Subhas University of Technology (NSUT)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1983,
    rating: 5,
  },
  {
    name: "Jamia Millia Islamia – Faculty of Engineering and Technology",
   // "./jamia-millia-islamia-664c6ed9f1569",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1920,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT) Delhi",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 5,
  },
  {
    name: "Indraprastha Institute of Information Technology (IIIT) Delhi",
   // "https://www.iiitd.ac.in/",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 5,
  },
  {
    name: "Indira Gandhi Delhi Technical University for Women (IGDTUW)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2012,
    rating: 5,
  },
  {
    name: "Guru Gobind Singh Indraprastha University (GGSIPU)",
   // "http://www.ipu.ac.in/",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1998,
    rating: 5,
  },
  {
    name: "GB Pant Government Engineering College",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1937,
    rating: 4,
  },

  // Top Private and GGSIPU-Affiliated Engineering Colleges
  {
    name: "Maharaja Agrasen Institute of Technology (MAIT)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "GGSIPU"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Maharaja Surajmal Institute of Technology (MSIT)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "GGSIPU"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Bharati Vidyapeeth’s College of Engineering (BVCOE)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Bhagwan Parshuram Institute of Technology (BPIT)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "GGSIPU"],
    established: 2000,
    rating: 4,
  },
  {
    name: "HMR Institute of Technology and Management",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2002,
    rating: 4,
  },
  {
    name: "Ambedkar Institute of Advanced Communication Technologies and Research",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2000,
    rating: 4,
  },
  {
    name: "Northern India Engineering College (NIEC)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2001,
    rating: 4,
  },
  {
    name: "Amity School of Engineering and Technology",
   // "",
    city: "Delhi NCR",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2003,
    rating: 4,
  },
  {
    name: "JIMS Engineering Management Technical Campus (Greater Noida/Delhi NCR)",
   // "",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2007,
    rating: 4,
  },
  {
    name: "Vivekananda Institute of Professional Studies (VIPS-TC)",
   // "",
    city: "Delhi",
    state: "Delhi",
    type: "Private",
    accreditations: ["AICTE", "GGSIPU"],
    established: 2002,
    rating: 4,
  },

  // Gujarat
    // Top Government and Premier Institutes
  {
    name: "Indian Institute of Technology (IIT) Gandhinagar",
   // "./indian-institute-of-technology-gandhinagar-664c6ed9d9f6e",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2008,
    rating: 5,
  },
  {
    name: "Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat",
   // "./sardar-vallabhbhai-national-institute-of-technology--svnit-sur-664c6ed9d9f32",
    city: "Surat",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1961,
    rating: 5,
  },
  {
    name: "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT), Gandhinagar",
   // "./dhirubhai-institute-of-information-and-communication-technology-(da-iict)-664c6ed9d95ac",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2001,
    rating: 5,
  },
  {
    name: "Pandit Deendayal Energy University (PDEU), Gandhinagar",
   // "./-pandit-deendayal-petroleum-university--664c6ed9da2fa",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2007,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Vadodara",
   // "",
    city: "Vadodara",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2013,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Surat",
   // "",
    city: "Surat",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2017,
    rating: 4,
  },
  {
    name: "L.D. College of Engineering",
   // "",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1948,
    rating: 4,
  },
  {
    name: "Vishwakarma Government Engineering College",
   // "",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1931,
    rating: 4,
  },
  // Government Engineering Colleges in Multiple Cities
  {
    name: "Government Engineering College, Rajkot",
   // "",
    city: "Rajkot",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2004,
    rating: 4,
  },
  {
    name: "Government Engineering College, Bhavnagar",
   // "",
    city: "Bhavnagar",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 3,
  },
  {
    name: "Government Engineering College, Bharuch",
   // "",
    city: "Bharuch",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 3,
  },
  {
    name: "Government Engineering College, Dahod",
   // "",
    city: "Dahod",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2004,
    rating: 3,
  },
  {
    name: "Government Engineering College, Gandhinagar",
   // "",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2004,
    rating: 3,
  },
  {
    name: "Government Engineering College, Godhra",
   // "",
    city: "Godhra",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 3,
  },
  {
    name: "Government Engineering College, Valsad",
   // "",
    city: "Valsad",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 3,
  },
  {
    name: "Government Engineering College, Modasa",
   // "",
    city: "Modasa",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 3,
  },
  {
    name: "Government Engineering College, Palanpur",
   // "",
    city: "Palanpur",
    state: "Gujarat",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 3,
  },

  // Prominent Private Engineering Colleges
  {
    name: "Nirma University",
   // "",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2003,
    rating: 5,
  },
  {
    name: "Charotar Institute of Technology",
   // "",
    city: "Anand",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2000,
    rating: 4,
  },
  {
    name: "A.D. Patel Institute of Technology (ADIT)",
   // "",
    city: "Anand",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Silver Oak College of Engineering and Technology",
   // "",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 4,
  },
  {
    name: "Swaminarayan College of Engineering and Technology",
   // "",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2001,
    rating: 4,
  },
  {
    name: "Vadodara Institute of Engineering",
   // "",
    city: "Vadodara",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2000,
    rating: 4,
  },
  {
    name: "Shantilal Shah Engineering College",
   // "",
    city: "Bhavnagar",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1988,
    rating: 4,
  },
  {
    name: "SPB Patel Engineering College",
   // "",
    city: "Mehsana",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2003,
    rating: 4,
  },
  {
    name: "Shroff S.R. Rotary Institute of Chemical Technology",
   // "",
    city: "Gandhinagar",
    state: "Gujarat",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2000,
    rating: 4,
  },

  // Haryana
  // Top Government Engineering Colleges
  {
    name: "National Institute of Technology (NIT), Kurukshetra",
   // "",
    city: "Kurukshetra",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1963,
    rating: 5,
  },
  {
    name: "J.C. Bose University of Science and Technology (YMCA), Faridabad",
   // "",
    city: "Faridabad",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1969,
    rating: 5,
  },
  {
    name: "Deenbandhu Chhotu Ram University of Science and Technology (DCRUST), Murthal",
   // "",
    city: "Murthal",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1987,
    rating: 5,
  },
  {
    name: "Kurukshetra University – Institute of Engineering & Technology, Kurukshetra",
   // "",
    city: "Kurukshetra",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1987,
    rating: 4,
  },
  {
    name: "Guru Jambheshwar University of Science and Technology (GJU), Hisar",
   // "",
    city: "Hisar",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1995,
    rating: 4,
  },
  {
    name: "State Institute of Engineering & Technology, Nilokheri",
   // "",
    city: "Nilokheri",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4,
  },
  {
    name: "Rao Birendar Singh State Institute of Engineering & Technology, Rewari",
   // "",
    city: "Rewari",
    state: "Haryana",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2017,
    rating: 3,
  },

  // Notable Private and Deemed Universities
  {
    name: "Amity University, Gurugram",
   // "",
    city: "Gurugram",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2005,
    rating: 4,
  },
  {
    name: "Manav Rachna International Institute of Research & Studies, Faridabad",
   // "",
    city: "Faridabad",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2013,
    rating: 4,
  },
  {
    name: "K.R. Mangalam University, Gurugram",
   // "",
    city: "Gurugram",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2013,
    rating: 4,
  },
  {
    name: "The NorthCap University, Gurugram",
   // "",
    city: "Gurugram",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1996,
    rating: 4,
  },
  {
    name: "Maharishi Markandeshwar University, Mullana, Ambala",
   // "",
    city: "Mullana",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1993,
    rating: 4,
  },
  {
    name: "Jind Institute of Engineering and Technology (JIET), Jind",
   // "",
    city: "Jind",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Apeejay Stya University, Gurugram",
   // "",
    city: "Gurugram",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "Echelon Institute of Technology, Faridabad",
   // "",
    city: "Faridabad",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 4,
  },

  // Other Prominent Colleges
  {
    name: "Shri Ram Institute Of Management And Technology, Palwal",
   // "",
    city: "Palwal",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2005,
    rating: 4,
  },
  {
    name: "BML Munjal University, Gurugram",
   // "",
    city: "Gurugram",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2014,
    rating: 4,
  },
  {
    name: "Om Sterling Global University, Hisar",
   // "",
    city: "Hisar",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4,
  },
  {
    name: "Swami Devi Dayal Institute of Engineering and Technology, Panchkula",
   // "",
    city: "Panchkula",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1985,
    rating: 4,
  },
  {
    name: "BRCM College of Engineering and Technology, Bahal",
   // "",
    city: "Bahal",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Sonepat College of Engineering & Technology",
   // "",
    city: "Sonepat",
    state: "Haryana",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2002,
    rating: 4,
  },
  // Jharkhand
   // Top Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Dhanbad (formerly ISM)",
   // "./indian-institute-of-technology-664c6ed9dc611",
    city: "Dhanbad",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1926,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT) Jamshedpur",
   // "",
    city: "Jamshedpur",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1960,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 5,
  },
  {
    name: "Birsa Institute of Technology (BIT) Sindri, Dhanbad",
   // "",
    city: "Dhanbad",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1949,
    rating: 5,
  },
  {
    name: "National Institute of Advanced Manufacturing Technology (NIAMT), Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2007,
    rating: 4,
  },
  {
    name: "Government Engineering College, Ramgarh",
   // "",
    city: "Ramgarh",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2015,
    rating: 4,
  },
  {
    name: "Chaibasa Engineering College, Techno India Group",
   // "",
    city: "Chaibasa",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },
  {
    name: "Dumka Engineering College, Dumka",
   // "",
    city: "Dumka",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2013,
    rating: 4,
  },
  {
    name: "University College of Engineering and Technology, Vinoba Bhave University, Hazaribag",
   // "",
    city: "Hazaribag",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1992,
    rating: 4,
  },
  {
    name: "Nilamber Pitamber University Engineering College",
   // "",
    city: "Daltonganj",
    state: "Jharkhand",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1992,
    rating: 3,
  },

  // Top Private Engineering Colleges
  {
    name: "Birla Institute of Technology (BIT) Mesra, Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1955,
    rating: 5,
  },
  {
    name: "Arka Jain University, Jamshedpur",
   // "",
    city: "Jamshedpur",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Amity University, Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Cambridge Institute of Technology (CIT), Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2002,
    rating: 4,
  },
  {
    name: "R.V.S College of Engineering and Technology (RVSCET), Jamshedpur",
   // "",
    city: "Jamshedpur",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2007,
    rating: 4,
  },
  {
    name: "Alice Institute of Technology, Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 3,
  },
  {
    name: "Ramgarh Engineering College, Ramgarh",
   // "",
    city: "Ramgarh",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2012,
    rating: 3,
  },
  {
    name: "KK College of Engineering and Management, Dhanbad",
   // "",
    city: "Dhanbad",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2004,
    rating: 3,
  },
  {
    name: "Sai Nath University, Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2012,
    rating: 3,
  },
  {
    name: "Usha Martin University, Ranchi",
   // "",
    city: "Ranchi",
    state: "Jharkhand",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2012,
    rating: 3,
  },

  // Karnataka
   // Top Government Engineering Colleges
  {
    name: "National Institute of Technology (NIT) Surathkal",
   // "https://www.nitk.ac.in/",
    city: "Surathkal",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1960,
    rating: 5,
  },
  {
    name: "Indian Institute of Technology (IIT) Dharwad",
   // "https://iitdh.ac.in/",
    city: "Dharwad",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2016,
    rating: 5,
  },
  {
    name: "University Visvesvaraya College of Engineering (UVCE), Bangalore",
   // "https://uvce.ac.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1917,
    rating: 5,
  },
  {
    name: "Visvesvaraya Technological University (VTU), Belagavi",
   // "https://vtu.ac.in/",
    city: "Belagavi",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1998,
    rating: 5,
    note: "Affiliates 220+ colleges",
  },
  {
    name: "Government Engineering College, Bangalore",
   // "",
    city: "Bangalore",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1965,
    rating: 4,
  },
  {
    name: "Government Engineering College, Mysore",
   // "",
    city: "Mysore",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1956,
    rating: 4,
  },
  {
    name: "Government Engineering College, Hassan",
   // "",
    city: "Hassan",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1960,
    rating: 4,
  },
  {
    name: "Government Engineering College, Mangalore",
   // "",
    city: "Mangalore",
    state: "Karnataka",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1960,
    rating: 4,
  },

  // Premier Private Engineering Colleges
  {
    name: "Manipal Institute of Technology (MIT), Manipal",
   // "https://manipal.edu/mit.html",
    city: "Manipal",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1957,
    rating: 5,
  },
  {
    name: "RV College of Engineering (RVCE), Bangalore",
   // "https://rvce.edu.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1963,
    rating: 5,
  },
  {
    name: "MS Ramaiah Institute of Technology, Bangalore",
   // "https://msrit.edu.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1962,
    rating: 5,
  },
  {
    name: "PES University, Bangalore",
   // "https://www.pes.edu/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1972,
    rating: 5,
  },
  {
    name: "Jain University, Bangalore",
   // "https://www.jainuniversity.ac.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1990,
    rating: 4,
  },
  {
    name: "Siddaganga Institute of Technology, Tumkur",
   // "https://www.sit.ac.in/",
    city: "Tumkur",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1963,
    rating: 4,
  },
  {
    name: "NMAM Institute of Technology, Nitte",
   // "https://nmamit.nitte.edu.in/",
    city: "Nitte",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1986,
    rating: 4,
  },

  // Other Notable Colleges
  {
    name: "Alva’s Institute of Engineering & Technology (AIET), Mijar",
   // "",
    city: "Mijar",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Nagarjuna College of Engineering & Technology, Bangalore",
   // "",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1997,
    rating: 4,
  },
  {
    name: "Christ University, Bangalore",
   // "https://christuniversity.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["UGC", "AICTE"],
    established: 1969,
    rating: 4,
  },
  {
    name: "BMS College of Engineering, Bangalore",
   // "https://bmsce.ac.in/",
    city: "Bangalore",
    state: "Karnataka",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1946,
    rating: 5,
  },
  // Madhya Pradesh
 // Top Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Indore",
   // "https://www.iiti.ac.in",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2009,
    rating: 5,
  },
  {
    name: "Maulana Azad National Institute of Technology (MANIT)",
   // "https://www.manit.ac.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1960,
    rating: 5,
  },
  {
    name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management (ABVIIITM)",
   // "https://iiitm.ac.in",
    city: "Gwalior",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2005,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology Design and Manufacturing (IIITDM)",
   // "https://www.iiitdmj.ac.in",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2005,
    rating: 5,
  },
  {
    name: "Jabalpur Engineering College",
   // "http://jecin.jec.ac.in",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1947,
    rating: 4,
  },
  {
    name: "Rewa Engineering College",
   // "https://rewaenggcollege.ac.in",
    city: "Rewa",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1964,
    rating: 4,
  },
  {
    name: "Indira Gandhi Engineering College",
   // "",
    city: "Sagar",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1981,
    rating: 4,
  },
  {
    name: "SGS Institute of Technology & Science",
   // "https://www.sgsits.ac.in",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2001,
    rating: 4,
  },

  // Leading Private Engineering Colleges
  {
    name: "Lakshmi Narain College of Technology (LNCT)",
   // "https://lnct.ac.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Lakshmi Narain College of Technology (LNCT) Jabalpur",
   // "https://lnct.ac.in",
    city: "Jabalpur",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Amity University",
   // "https://www.amity.edu/central",
    city: "Gwalior",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2008,
    rating: 4,
  },
  {
    name: "SAGE University",
   // "https://www.sageuniversity.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2017,
    rating: 4,
  },
  {
    name: "SAGE University Indore",
   // "https://indore.sageuniversity.in",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2017,
    rating: 4,
  },
  {
    name: "Medi-Caps University",
   // "https://www.medicaps.ac.in",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2009,
    rating: 4,
  },
  {
    name: "Patel Group of Institutions",
   // "",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2000,
    rating: 4,
  },
  {
    name: "Sagar Institute of Science & Technology (SISTec)",
   // "https://www.sistec.edu.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2000,
    rating: 4,
  },
  {
    name: "Truba Group of Institutes",
   // "https://www.trubainstitute.ac.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1998,
    rating: 4,
  },
  {
    name: "Jaypee University of Engineering & Technology",
   // "https://www.juet.ac.in",
    city: "Guna",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2003,
    rating: 4,
  },
  {
    name: "Madhyanchal Professional University",
   // "https://www.mpu.ac.in",
    city: "Bhopal",
    state: "Madhya Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2016,
    rating: 4,
  },

  // Maharashtra
  // Top Government and Central Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Bombay",
   // "https://www.iitb.ac.in/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1958,
    rating: 5,
  },
  {
    name: "Visvesvaraya National Institute of Technology (VNIT)",
   // "https://vnit.ac.in/",
    city: "Nagpur",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1960,
    rating: 5,
  },
  {
    name: "Institute of Chemical Technology (ICT)",
   // "https://www.ictmumbai.edu.in/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1933,
    rating: 5,
  },
  {
    name: "Defence Institute of Advanced Technology (DIAT)",
   // "https://diat.ac.in/",
    city: "Pune",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1986,
    rating: 5,
  },
  {
    name: "College of Engineering Pune (COEP)",
   // "https://coep.org.in/",
    city: "Pune",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1854,
    rating: 5,
  },
  {
    name: "Veermata Jijabai Technological Institute (VJTI)",
   // "https://vjti.ac.in/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1887,
    rating: 5,
  },
  {
    name: "Government College of Engineering, Aurangabad",
   // "https://gcoea.ac.in/",
    city: "Aurangabad",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1960,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Amravati",
   // "https://coeamravati.ac.in/",
    city: "Amravati",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Karad",
   // "https://gcoekar.ac.in/",
    city: "Karad",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1960,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Chandrapur",
   // "https://gcoec.ac.in/",
    city: "Chandrapur",
    state: "Maharashtra",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1996,
    rating: 4,
  },

  // Leading Private and Autonomous Engineering Colleges
  {
    name: "MIT World Peace University (MIT WPU)",
   // "https://mitwpu.edu.in/",
    city: "Pune",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2017,
    rating: 5,
  },
  {
    name: "Dr. D.Y. Patil Institute of Technology",
   // "https://www.dypatil.edu/",
    city: "Pune",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2001,
    rating: 5,
  },
  {
    name: "Bharati Vidyapeeth’s College of Engineering",
   // "https://bvuniversity.edu.in/",
    city: "Pune",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Vishwakarma Institute of Technology",
   // "https://vit.edu/",
    city: "Pune",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Rajarambapu Institute of Technology",
   // "https://ritindia.edu/",
    city: "Sangli",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  {
    name: "Fr. Conceicao Rodrigues College of Engineering (FCRCE)",
   // "https://www.frcrce.ac.in/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1984,
    rating: 4,
  },
  {
    name: "SPCE - Sardar Patel College of Engineering",
   // "https://spce.ac.in/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1962,
    rating: 5,
  },
  {
    name: "Ramrao Adik Institute of Technology",
   // "https://rait.ac.in/",
    city: "Navi Mumbai",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1991,
    rating: 4,
  },
  {
    name: "Thadomal Shahani Engineering College",
   // "https://www.tsec.edu/",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1983,
    rating: 4,
  },
  // Punjab
   // Top Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Ropar",
   // "https://www.iitrpr.ac.in",
    city: "Rupnagar",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2009,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT) Jalandhar",
   // "https://www.nitj.ac.in",
    city: "Jalandhar",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1987,
    rating: 5,
  },
  {
    name: "Punjab Engineering College (PEC)",
   // "https://pec.ac.in",
    city: "Chandigarh",
    state: "Chandigarh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1921,
    rating: 5,
  },
  {
    name: "Guru Nanak Dev Engineering College (GNDEC)",
   // "https://www.gndec.ac.in",
    city: "Ludhiana",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1956,
    rating: 4,
  },
  {
    name: "Baba Banda Singh Bahadur Engineering College",
   // "",
    city: "Fatehgarh Sahib",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1992,
    rating: 4,
  },
  {
    name: "Government Engineering College",
   // "",
    city: "Bathinda",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1990,
    rating: 3,
  },
  {
    name: "Central Institute of Hand Tools (CIHT)",
   // "",
    city: "Jalandhar",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1963,
    rating: 3,
  },

  // Leading Private Engineering Colleges
  {
    name: "Lovely Professional University (LPU)",
   // "https://www.lpu.in",
    city: "Phagwara",
    state: "Punjab",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2005,
    rating: 4,
  },
  {
    name: "Thapar Institute of Engineering and Technology (TIET)",
   // "https://www.thapar.edu",
    city: "Patiala",
    state: "Punjab",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1956,
    rating: 5,
  },
  {
    name: "Chandigarh University",
   // "https://www.cuchd.in",
    city: "Chandigarh",
    state: "Chandigarh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2012,
    rating: 4,
  },
  {
    name: "Chitkara University",
   // "https://www.chitkara.edu.in",
    city: "Chandigarh",
    state: "Chandigarh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2009,
    rating: 4,
  },
  {
    name: "Chandigarh Group of Colleges",
   // "https://www.cgc.edu.in",
    city: "Landran",
    state: "Punjab",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2001,
    rating: 3,
  },
  {
    name: "Rayat Bahra University",
   // "https://www.rayatbahrauniversity.edu.in",
    city: "Mohali",
    state: "Punjab",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2012,
    rating: 3,
  },
  {
    name: "Rayat Bahra Institute of Engineering & Biotechnology",
   // "https://www.rayatbahrainstitute.edu.in",
    city: "Mohali",
    state: "Punjab",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2008,
    rating: 3,
  },
  {
    name: "I.K. Gujral Punjab Technical University (PTU)",
   // "https://www.ptu.ac.in",
    city: "Jalandhar",
    state: "Punjab",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1997,
    rating: 4,
  },
  // Tamil Nadu
  // Top Government Engineering Colleges
  {
    name: "Government College of Technology",
   // "https://www.gct.ac.in",
    city: "Coimbatore",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1945,
    rating: 5,
  },
  {
    name: "Alagappa Chettiar College of Engineering and Technology",
   // "https://www.alagappa.ac.in/engineering",
    city: "Karaikudi",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1952,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Salem",
   // "https://www.gcesalem.edu.in",
    city: "Salem",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1966,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Tirunelveli",
   // "https://www.tce.ac.in",
    city: "Tirunelveli",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1981,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Erode",
   // "https://www.gce-ec.edu.in",
    city: "Erode",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Thanthai Periyar Government Institute of Technology",
   // "https://www.tpget.ac.in",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Government College of Engineering, Bargur",
   // "",
    city: "Bargur",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 3,
  },
  {
    name: "Government College of Engineering, Thanjavur",
   // "",
    city: "Thanjavur",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 3,
  },
  {
    name: "Government College of Engineering, Bodinayakkanur",
   // "",
    city: "Bodinayakkanur",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 3,
  },
  {
    name: "Government College of Engineering, Dharmapuri",
   // "",
    city: "Dharmapuri",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2018,
    rating: 3,
  },
  {
    name: "Government College of Engineering, Srirangam",
   // "",
    city: "Srirangam",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4,
  },

  // Renowned Private Engineering Colleges
  {
    name: "Indian Institute of Technology Madras (IIT Madras)",
   // "https://www.iitm.ac.in",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1959,
    rating: 5,
  },
  {
    name: "National Institute of Technology Tiruchirappalli (NIT Trichy)",
   // "https://www.nitt.edu",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1964,
    rating: 5,
  },
  {
    name: "Vellore Institute of Technology (VIT)",
   // "https://vit.ac.in",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1984,
    rating: 5,
  },
  {
    name: "SRM Institute of Science and Technology",
   // "https://www.srmist.edu.in",
    city: "Kattankulathur",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1985,
    rating: 5,
  },
  {
    name: "SSN College of Engineering",
   // "https://www.ssn.edu.in",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1996,
    rating: 5,
  },
  {
    name: "PSG College of Technology",
   // "https://www.psgtech.edu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1951,
    rating: 5,
  },
  {
    name: "Sathyabama Institute of Science and Technology",
   // "https://sathyabama.ac.in",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1987,
    rating: 5,
  },
  {
    name: "Thiagarajar College of Engineering",
   // "https://www.tce.edu",
    city: "Madurai",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1957,
    rating: 5,
  },
  {
    name: "Hindustan Institute of Technology and Science",
   // "https://hindustanuniv.ac.in",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1985,
    rating: 4,
  },
  {
    name: "Kumaraguru College of Technology",
   // "https://www.kct.ac.in",
    city: "Coimbatore",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1984,
    rating: 4,
  },
  {
    name: "Vel Tech Rangarajan Dr. Sagunthala R&D Institute",
   // "https://veltech.edu.in",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 1997,
    rating: 4,
  },

  // Uttar Pradesh
 // Top Government / Central Institutes
  {
    name: "Indian Institute of Technology (IIT) Kanpur",
   // "https://iitk.ac.in",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1959,
    rating: 5,
  },
  {
    name: "Indian Institute of Technology (BHU) Varanasi",
   // "http://iitbhu.ac.in",
    city: "Varanasi",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1919,
    rating: 5,
  },
  {
    name: "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
   // "https://mnnit.ac.in",
    city: "Allahabad",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1961,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Allahabad",
   // "https://iiita.ac.in",
    city: "Allahabad",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1999,
    rating: 5,
  },
  {
    name: "Rajiv Gandhi Institute of Petroleum Technology (RGIPT), Amethi",
   // "https://rgipt.ac.in",
    city: "Amethi",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Harcourt Butler Technical University (HBTU), Kanpur",
   // "https://hbtu.ac.in",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1921,
    rating: 4,
  },
  {
    name: "Aligarh Muslim University (AMU)",
   // "https://www.amu.ac.in",
    city: "Aligarh",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1920,
    rating: 4,
  },
  
  // Other Government Colleges
  {
    name: "Madan Mohan Malaviya Engineering College",
   // "",
    city: "Gorakhpur",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1962,
    rating: 4,
  },
  {
    name: "Government College, Faizabad",
   // "",
    city: "Faizabad",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1988,
    rating: 3,
  },
  {
    name: "Uttar Pradesh Textile Technology Institute",
   // "",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1954,
    rating: 3,
  },
  {
    name: "Institute of Engineering & Rural Technology",
   // "",
    city: "Allahabad",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1963,
    rating: 3,
  },
  {
    name: "B.B.S. College of Engineering & Technology",
   // "",
    city: "Fatehpur",
    state: "Uttar Pradesh",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1998,
    rating: 3,
  },

  // Private / Deemed Universities
  {
    name: "Amity University",
   // "https://www.amity.edu",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2005,
    rating: 4,
  },
  {
    name: "Galgotias University",
   // "https://www.galgotiasuniversity.edu.in",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2011,
    rating: 4,
  },
  {
    name: "Jaypee Institute of Information Technology (JIIT)",
   // "https://jiit.ac.in",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2001,
    rating: 4,
  },
  {
    name: "Shobhit University",
   // "https://www.shobhituniversity.ac.in",
    city: "Meerut",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2006,
    rating: 3,
  },
  {
    name: "Shiv Nadar University",
   // "https://shivnadaru.com",
    city: "Gautam Buddha Nagar",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2011,
    rating: 4,
  },
  {
    name: "Noida Institute of Engineering and Technology (NIET)",
   // "https://niet.co.in",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2001,
    rating: 4,
  },
  {
    name: "Galgotias College of Engineering & Technology",
   // "https://www.galgotiasuniversity.edu.in/schools/engineering-computer-applied-sciences",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2011,
    rating: 4,
  },
  // Top Government Engineering Colleges - Arunachal Pradesh
  {
    name: "National Institute of Technology (NIT) Arunachal Pradesh",
   // "https://nitap.ac.in",
    city: "Jote (Papum Pare)",
    state: "Arunachal Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2010,
    rating: 4,
  },
  {
    name: "North Eastern Regional Institute of Science and Technology (NERIST)",
   // "https://nerist.ac.in",
    city: "Nirjuli (Itanagar)",
    state: "Arunachal Pradesh",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1984,
    rating: 4,
  },
  {
    name: "Arunachal University of Studies",
   // "https://www.aus.edu.in",
    city: "Namsai",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2012,
    rating: 3,
  },

  // Top Private Engineering Colleges - Arunachal Pradesh
  {
    name: "Arunodaya University",
   // "http://arunodayauniversity.ac.in",
    city: "Lekhi, Naharlagun (Itanagar)",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2014,
    rating: 3,
  },
  {
    name: "Himalayan University",
   // "https://himalayanuniversity.edu.in",
    city: "Jullang Village (Itanagar)",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2013,
    rating: 3,
  },
  {
    name: "Apex Professional University (APU)",
   // "https://apexprofessionaluniversity.ac.in",
    city: "Pasighat (Smart City)",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2019,
    rating: 3,
  },
  {
    name: "NEFTU (North East Frontier Technical University)",
   // "https://neftu.ac.in",
    city: "Aalo (West Siang)",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2014,
    rating: 3,
  },
  {
    name: "Indira Gandhi Technological and Medical Sciences University (IGTAMSU)",
   // "https://igtamsu.edu.in",
    city: "Ziro (Lower Subansiri District)",
    state: "Arunachal Pradesh",
    type: "Private",
    accreditations: ["UGC"],
    established: 2012,
    rating: 3,
  },
   // Top Government Engineering Colleges
  {
    name: "Indian Institute of Technology (IIT) Guwahati",
   // "https://iitg.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1994,
    rating: 5,
  },
  {
    name: "National Institute of Technology (NIT) Silchar",
   // "https://www.nits.ac.in",
    city: "Silchar",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1967,
    rating: 5,
  },
  {
    name: "Indian Institute of Information Technology (IIIT) Guwahati",
   // "https://www.iiitg.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2013,
    rating: 4,
  },
  {
    name: "Assam Engineering College",
   // "https://aecassam.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1955,
    rating: 4,
  },
  {
    name: "Jorhat Engineering College",
   // "http://jecassam.in",
    city: "Jorhat",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1959,
    rating: 3,
  },
  {
    name: "Bineswar Brahma Engineering College",
   // "",
    city: "Kokrajhar",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 3,
  },
  {
    name: "Barak Valley Engineering College",
   // "",
    city: "Silchar",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 3,
  },
  {
    name: "Tezpur University (School of Engineering)",
   // "https://www.tezu.ernet.in",
    city: "Tezpur",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 1994,
    rating: 4,
  },
  {
    name: "Central Institute of Technology (CIT), Kokrajhar",
   // "https://cit.ac.in",
    city: "Kokrajhar",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 3,
  },
  {
    name: "Assam Science and Technology University",
   // "https://astu.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Government",
    accreditations: ["AICTE", "UGC"],
    established: 2010,
    rating: 4,
  },

  // Notable Private and Public-Private Engineering Colleges
  {
    name: "Assam Don Bosco University",
   // "https://www.dbuniversity.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["UGC"],
    established: 2008,
    rating: 4,
  },
  {
    name: "Assam Down Town University (ADTU)",
   // "https://www.adtu.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["UGC"],
    established: 2010,
    rating: 3,
  },
  {
    name: "Royal Global University",
   // "https://royalglobaluniversity.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["UGC"],
    established: 2013,
    rating: 4,
  },
  {
    name: "Jorhat Institute of Science & Technology",
   // "https://jistassam.in",
    city: "Jorhat",
    state: "Assam",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2009,
    rating: 3,
  },
  {
    name: "Girijananda Chowdhury Institute of Management & Technology",
   // "https://gcimt.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 4,
  },
  {
    name: "Don Bosco College of Engineering and Technology",
   // "https://dbcet.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2008,
    rating: 3,
  },
  {
    name: "Scholar's Institute of Technology and Management",
   // "https://scholarscollege.ac.in",
    city: "Guwahati",
    state: "Assam",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 3,
  },
  // goa 
    {
    name: "Goa College of Engineering",
   // "https://www.gec.ac.in/",
    city: "Ponda",
    state: "Goa",
    type: "Government",
    accreditations: ["AICTE"],
    established: 1967,
    rating: 4.5,
  },
  {
    name: "Indian Institute Of Technology Goa",
   // "http://www.iitgoa.ac.in/",
    city: "Ponda",
    state: "Goa",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2016,
    rating: 4.1,
  },
  {
    name: "Shree Rayeshwar Institute of Engineering & Information Technology",
   // "http://ritgoa.ac.in/",
    city: "Shiroda",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1994,
    rating: 3.9,
  },
  {
    name: "Padre Conceicao College of Engineering",
   // "https://pccegoa.edu.in/",
    city: "Verna",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE"],
    established: 1999,
    rating: 3.3,
  },
  {
    name: "Agnel Institute of Technology and Design",
   // "https://aitdgoa.edu.in/",
    city: "Assagao",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2009,
    rating: 4.2,
  },
  {
    name: "Institute Of Maritime Studies",
   // "http://imsgoa.org/",
    city: "Vasco Da Gama",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2000,
    rating: 4.4,
  },
  {
    name: "National Institute of Technology (NIT) Goa",
   // "https://nitgoa.ac.in/",
    city: "Ponda",
    state: "Goa",
    type: "Government",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 4.0,
  },
  {
    name: "Birla Institute of Technology & Science (BITS), Pilani – Goa Campus",
   // "https://www.bits-pilani.ac.in/goa/",
    city: "South Goa",
    state: "Goa",
    type: "Private/Deemed",
    accreditations: ["AICTE", "UGC"],
    established: 2004,
    rating: 4.3,
  },
  {
    name: "Parul University",
   // "https://paruluniversity.ac.in/",
    city: "Quepem",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE", "UGC"],
    established: 2013,
    rating: 3.5,
  },
  {
    name: "Don Bosco College of Engineering",
   // "https://dbcem.edu.in/",
    city: "Fatorda, Margao",
    state: "Goa",
    type: "Private",
    accreditations: ["AICTE"],
    established: 2010,
    rating: 3.8,
  },
  {
    name: "Goa University",
   // "https://www.unigoa.ac.in/",
    city: "Taleigao Plateau",
    state: "Goa",
    type: "Government",
    accreditations: ["UGC"],
    established: 1985,
    rating: 3.9,
  },
];



// Example pastel backgrounds
const cardColors = [
  "from-pink-100/70 via-pink-200/70 to-pink-300/70",
  "from-green-100/70 via-green-200/70 to-green-300/70",
  "from-yellow-100/70 via-yellow-200/70 to-yellow-300/70",
  "from-blue-100/70 via-blue-200/70 to-blue-300/70",
  "from-purple-100/70 via-purple-200/70 to-purple-300/70",
  "from-rose-100/70 via-rose-200/70 to-rose-300/70",
  "from-cyan-100/70 via-cyan-200/70 to-cyan-300/70",
];


export default function TopEngineeringColleges() {
  const [selectedState, setSelectedState] = useState("All");

  // Unique states
  const states = useMemo(() => {
    const uniqueStates = Array.from(new Set(colleges.map((c) => c.state))).sort();
    return ["All", ...uniqueStates];
  }, []);

  // Filtered data
  const filteredColleges = useMemo(() => {
    if (selectedState === "All") return colleges;
    return colleges.filter((c) => c.state === selectedState);
  }, [selectedState]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-indigo-100 py-16 px-6 sm:px-12 lg:px-24 relative overflow-hidden">
      {/* Background Floating Shapes */}
      <div className="absolute inset-0 -z-10 opacity-30">
        <div className="absolute top-20 left-1/4 w-96 h-96 bg-pink-200 rounded-full blur-3xl"></div>
        <div className="absolute bottom-20 right-1/4 w-[28rem] h-[28rem] bg-blue-200 rounded-full blur-3xl"></div>
      </div>

      <h1 className="text-5xl font-extrabold text-center text-gray-900 mb-16 tracking-tight drop-shadow-xl uppercase">
        Top Engineering Colleges in India
      </h1>

      {/* Filter */}
      <div className="max-w-lg mx-auto mb-16">
        <label
          htmlFor="stateFilter"
          className="block mb-4 font-semibold text-gray-800 text-lg tracking-wide"
        >
          Filter by State
        </label>
        <select
          id="stateFilter"
          className="w-full rounded-2xl border border-gray-200 bg-white/60 backdrop-blur-md py-4 px-5 text-gray-900 font-semibold shadow-lg focus:outline-none focus:ring-4 focus:ring-indigo-300 focus:border-indigo-400 transition"
          value={selectedState}
          onChange={(e) => setSelectedState(e.target.value)}
        >
          {states.map((state) => (
            <option key={state} value={state} className="text-gray-900">
              {state}
            </option>
          ))}
        </select>
      </div>

      {/* Cards Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-12">
        {filteredColleges.length === 0 ? (
          <p className="col-span-full text-center text-gray-600 text-xl font-medium select-none animate-pulse">
            No colleges found for selected state.
          </p>
        ) : (
          filteredColleges.map((college, idx) => {
            const bgGradient = cardColors[idx % cardColors.length];
            return (
              <a
                key={college.url + idx}
                href={college.url}
                target="_blank"
                rel="noopener noreferrer"
                className={`relative group rounded-3xl border border-white/40 p-8 flex flex-col min-h-[340px] bg-gradient-to-br ${bgGradient} shadow-xl backdrop-blur-lg hover:scale-[1.05] transition-transform duration-300 overflow-hidden`}
              >
                {/* Glow ring hover */}
                <div className="absolute inset-0 rounded-3xl bg-gradient-to-r from-indigo-300 via-pink-300 to-yellow-200 opacity-0 group-hover:opacity-40 blur-xl transition duration-500"></div>

                <div className="flex items-center mb-5 relative z-10">
                  <AcademicCapIcon className="w-7 h-7 text-indigo-700 mr-3" />
                  <h2 className="font-extrabold text-lg text-gray-900 tracking-tight leading-snug">
                    {college.name}
                  </h2>
                  <span className="ml-auto text-xs font-semibold bg-indigo-50 border border-indigo-200 text-indigo-900 rounded-full px-3 py-1 shadow">
                    Since {college.established}
                  </span>
                </div>

                {/* Type */}
                <div className="mb-4 relative z-10">
                  {college.type && (
                    <span
                      className={`rounded-xl px-4 py-1 text-xs font-semibold shadow ${
                        college.type === "Government"
                          ? "bg-blue-100/80 text-blue-900"
                          : college.type === "Private"
                          ? "bg-pink-100/80 text-pink-900"
                          : "bg-green-100/80 text-green-900"
                      }`}
                    >
                      {college.type}
                    </span>
                  )}
                </div>

                {/* Tags */}
                <div className="flex flex-wrap gap-2 mb-6 z-10 relative">
                  {college.accreditations.map((tag, i) => (
                    <span
                      key={i}
                      className="bg-white/70 border border-gray-300 text-gray-900 rounded-full px-3 py-1 text-xs font-semibold shadow-sm hover:shadow-md hover:scale-105 transition cursor-default"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                {/* Location */}
                <div className="flex items-center gap-2 text-gray-800 font-semibold tracking-wide mt-auto relative z-10">
                  <MapPinIcon className="w-5 h-5 text-red-600" />
                  {college.city}, {college.state}
                </div>

                {/* Button */}
                <div className="mt-6 relative z-10">
                  <div className="inline-block px-5 py-2 rounded-full bg-indigo-600 text-white font-semibold text-sm shadow-md hover:bg-indigo-700 transition cursor-pointer">
                    Explore →
                  </div>
                </div>
              </a>
            );
          })
        )}
      </div>
    </div>
  );
}